# Generated by Django 3.0.8 on 2020-08-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etab',
            fields=[
                ('siret', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('nom_commercial', models.CharField(max_length=32, null=True)),
                ('voie', models.CharField(max_length=100, null=True)),
                ('code_postal', models.CharField(max_length=5)),
                ('commune', models.CharField(max_length=30)),
                ('code_insee', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Liste',
            fields=[
                ('rae', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('siren', models.CharField(max_length=9, null=True)),
                ('statut_traitement', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pdl',
            fields=[
                ('rae', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('voie', models.CharField(max_length=100, null=True)),
                ('code_postal', models.CharField(max_length=5)),
                ('commune', models.CharField(max_length=30)),
                ('code_insee', models.CharField(max_length=5, null=True)),
                ('siren', models.CharField(max_length=5)),
            ],
        ),
    ]
