# Generated by Django 3.0.8 on 2020-08-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctrlm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etab',
            name='siren',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
