# Generated by Django 3.0.8 on 2020-08-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctrlm', '0002_etab_siren'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etab',
            name='code_postal',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='etab',
            name='commune',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='etab',
            name='siren',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='liste',
            name='siren',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='pdl',
            name='code_postal',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='pdl',
            name='commune',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
